# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19bec1fdb1112a435069c123b15a05e4547460505818f28aa08d58394fb6a6193bd1e91ff9269816d87c9e972206031e182be33367f3990f8970c3d2e10a4b97

test:
  secret_key_base: c5999f1830711056291f14d263af5a63e2ea942de82faf6c1b61be93dd4d826e4c12801ae4a1eb523e864eddef9803aaecab7966a9ca03592feceffcc42bb57f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
